- assets/BD/sare.sql
- index.php
- inicio.php
Cambios en el menú así como en la pantalla principal y BD
> Cambios en el menú así como en la pantalla principal y BD

- view/solicitud/nuevo.php
Modificación de calculo de superficie del local
> Modificación de calculo de superficie del local

- view/solicitud/licencia.php
Repara el formato .pdf de la licencia.
> Hot fix detalles

- inicio.php
- model/sedatum/monitor.php
Se agregó la función que actualiza el ícono
> Se agregó la función que actualiza el ícono

- model/solicitud/fill.php
- view/sedatum/informe.php
Agrega los archivos a su respectiva pantalla, solo falta rellenar campos.
> Agrega archivos a imprimir

- controller/solicitud/funciones_solicitud.php
- model/solicitud/fill.php
- view/sedatum/informe.php
Modifica obtener datos generales
> Hotfix informe

- inicio.php
- model/sedatum/monitor.php
> Correcciones menores al push

- controller/solicitud/funciones_solicitud.php
- model/solicitud/fill.php
- view/sedatum/informe.php
Envía datos separados de establecimiento
> Hotfix establecimiento

- view/sedatum/informe.php
- view/sedatum/pdf_orden.php
Parte el string del dictamen en 2, una parte será el frente en el cuadro más pequeño y lo demás en la parte posterior del formato del informe.
> Fix observaciones del dictamen

- model/solicitud/create_documentos.php
- view/solicitud/nuevo.php
Agrega input para el archivo
Activa y desactiva required's
Muestra y oculta inputs
> Agrega input para comprobante de pago del número oficial

- pdf/sare/orden_pago_licencia.php
Crea la carpeta de pagos si es que no existe.
> Guarda el archivo en la carpeta de pagos.

- controller/solicitud/funciones_solicitud.php
- model/solicitud/create_documentos.php
- model/solicitud/modal_info_sol.php
Agrega el mensaje para solicitar número oficial
> Agrega solicita número oficial

- inicio.php
- model/sedatum/modal_gen_recibo.php
- model/solicitud/modal_info_sol.php
Modificación para impresión de ordenes
> Modificación para impresión de ordenes

- controller/solicitud/funciones_solicitud.php
- model/solicitud/fill.php
- pdf/sedatum/informe.php
Obtiene la fecha en la que recibe ventanilla
> Obtiene fecha en informe

- model/solicitud/save_img_map.php
- view/solicitud/nuevo.php
Creación de archivo para subir la captura de pantalla del mapa
> Creación de archivo para subir la captura de pantalla del mapa

- controller/solicitud/funciones_solicitud.php
- model/solicitud/create_documentos.php
Obtiene fecha de recibido en ventanilla
> Obtiene fecha recibido

- model/solicitud/create_documentos.php
- view/solicitud/nuevo.php
Modificación para carga de input en la imagen del mapa
> Modificación para carga de input en la imagen del mapa

- model/solicitud/create_documentos.php
> Actualiza create_documentos.php

- model/solicitud/create_documentos.php
- pdf/sedatum/informe.php
> Hotfix ruta mapa

- model/solicitud/modal_info_sol.php
Se agrego la imagen del mapa en el modal info
> Se agrego la imagen del mapa en el modal info

- view/solicitud/nuevo.php
Corrección de mask del registro
> Corrección de mask del registro

- model/sedatum/datos_persona_fisica.php
> Corrección CP

- pdf/sare/licencia.php
> Hotfix solicitudes

- model/solicitud/modal_info_sol.php
Quita los botones de aprobar y rechazar si ya finalizó la solicitud
> Quita botones de aprobar y rechazar

- controller/solicitud/funciones_update_solicitud.php
- model/solicitud/reinicia_solicitud.php
Crea modelo y controlador para reiniciar solicitudes
> Reinicia solicitud

- controller/solicitud/funciones_update_solicitud.php
- model/solicitud/reinicia_solicitud.php
> Borra corchetes de variable

- inicio.php
- model/solicitud/modal_info_sol.php
- model/solicitud/reinicia_solicitud.php
Se separo el domicilio en inputs independientes
> Se separo el domicilio en inputs independientes

- view/solicitud/nuevo.php
Corrección de error al momento de guardar documentos
> Corrección de error al momento de guardar documentos

- pdf/sare/fusare.php
> Ajusta detalles del template(espacios)

- controller/solicitud/funciones_update_solicitud.php
- model/solicitud/reinicia_solicitud.php
Actualiza funciones para reiniciar solicitudes
> Hotfix reinicia solicitud

- assets/css/bootstrap-treeview.css
- assets/js/bootstrap-treeview.js
- inicio.php
- model/solicitud/modal_info_sol.php
- view/solicitud/listado.php
Correcciones al momento de reiniciar solicitud
> Correcciones al momento de reiniciar solicitud

- inicio.php
- model/solicitud/modal_info_sol.php
- Agrega el width adecuado para su correcta visualización.
- Fix "padding-right" de "body" cuando se abre un modal desde una "dynamic-table".
> Fix input width

- inicio.php
- model/solicitud/modal_info_sol.php
-Agrega una función en la cual si no tiene datos la input; esta toma el placeholder como el ancho para que el usuario sepa que dato ingresar,  especificamente en los datos del domicilio..
> Fix ancho del placeholder en inputs

- inicio.php
- model/solicitud/modal_info_sol.php
- model/solicitud/update_documentos.php
Agrega scripts del drozone
Agrega html de la forma
Envia archivos al modelo
> Agrega form para nueva carga de documentos

- assets/js/bootstrap-treeview.js
- inicio.php
- model/solicitud/modal_info_sol.php
Muestra el botón de borrar archivo y de subir nuevos archivos al dar click en la opción de editar datos.
> Fix visibilidad de elementos

- model/solicitud/modal_info_sol.php
Envía el folio desde la forma que se encuentra en el modal info, en la pestaña de documentos.
> Envía folio para el CRUD

- model/solicitud/create_documentos.php
- model/solicitud/finalizar_solicitud.php
- view/solicitud/nuevo.php
Se adecuo la finalización de la solicitud
> Se adecuo la finalización de la solicitud

- view/solicitud/nuevo.php
> Se agrego folio a finalizar

- model/solicitud/delete_documento.php
- model/solicitud/finalizar_solicitud.php
- view/solicitud/nuevo.php
correcciones al momento de modificar archivos
> correcciones al momento de modificar archivos

- model/solicitud/delete_documento.php
- model/solicitud/delete_file.php
- view/solicitud/nuevo.php
Corrección al momento de enviar parámetros para eliminar el archivo
> Corrección al momento de enviar parámetros para eliminar el archivo

- inicio.php
- model/sedatum/actualiza_status.php
- model/sedatum/modal_com_uso.php
- model/sedatum/modal_gen_recibo.php
- model/sedatum/upload_doc_uso.php
Modificaciones en uso de suelo y folio de sedatum
> Modificaciones en uso de suelo y folio de sedatum

- assets/BD/sare.sql
- controller/solicitud/funciones_solicitud.php
- model/sedatum/actualiza_status.php
- model/solicitud/modal_info_sol.php
> Agrega folio sedatum

- inicio.php
- model/sedatum/modal_com_uso.php
- model/solicitud/modal_info_sol.php
Corrección de carga de uso de suelo
> Corrección de carga de uso de suelo
